### ISSUE TITLE
Error: Could not find or load main class java

### ISSUE THREAD

**Issue by yoyokunOffical** [PlutoSolutions/Future#106]
Error: Could not find or load main class java
java.lang.ClassNotFoundException: java
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)

**Comment by mr-nv** [comment]
fix your pc

**Comment by yoyokunOffical** [comment]
Pretty sure i got a good pc .-.

**Comment by mr-nv** [comment]
reinstall java

ср, 9 авг. 2023 г., 18:20 yoyokunOffical ***@***.***>:
