### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by dxeglow** [PlutoSolutions/Future#119]
Exception in thread "main" java.lang.NullPointerException
        at solutions.pluto.Utils.lambda$getMinecraftProfiles$0(Utils.java:24)
        at java.util.Map.forEach(Unknown Source)
        at solutions.pluto.Utils.getMinecraftProfiles(Utils.java:20)
        at solutions.pluto.InstallerFrame.<init>(InstallerFrame.java:76)
        at solutions.pluto.Bootstrap.main(Bootstrap.java:27)

**Comment by mr-nv** [comment]
хуй знает вручную устанавливай
